// <auto-generated />
using System.Reflection;
using AnseoConnect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AnseoConnect.Data.Migrations
{
    [DbContext(typeof(AnseoConnectDbContext))]
    [Migration("20260113095000_EpicB_Reports")]
    partial class EpicB_Reports
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            var snapshot = new AnseoConnectDbContextModelSnapshot();
            var method = typeof(AnseoConnectDbContextModelSnapshot).GetMethod("BuildModel", BindingFlags.Instance | BindingFlags.NonPublic);
            method!.Invoke(snapshot, new object[] { modelBuilder });
        }
    }
}

