// <auto-generated />
using System.Reflection;
using AnseoConnect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AnseoConnect.Data.Migrations
{
    [DbContext(typeof(AnseoConnectDbContext))]
    [Migration("20260112195138_CommsHubHardening")]
    partial class CommsHubHardening
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Delegate to the current model snapshot to keep the designer lightweight.
            var snapshot = new AnseoConnectDbContextModelSnapshot();
            var method = typeof(AnseoConnectDbContextModelSnapshot).GetMethod("BuildModel", BindingFlags.Instance | BindingFlags.NonPublic);
            method!.Invoke(snapshot, new object[] { modelBuilder });
        }
    }
}
